services:
  api:
    build:
      context: .
      dockerfile: TechStoreOrders.Api/Dockerfile
    container_name: tech-store-orders-api
    environment:
      ASPNETCORE_ENVIRONMENT: Development
      ConnectionStrings__DefaultConnection: Data Source=/data/techstore-orders.db
    ports:
      - "8080:8080"
    volumes:
      - sqlite_data:/data

volumes:
  sqlite_data:
