// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using TechStoreOrders.Infrastructure.Persistence;

#nullable disable

namespace TechStoreOrders.Infrastructure.Persistence.Migrations
{
    [DbContext(typeof(TechStoreDbContext))]
    [Migration("20260302121149_InitialCreate")]
    partial class InitialCreate
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder.HasAnnotation("ProductVersion", "10.0.3");

            modelBuilder.Entity("TechStoreOrders.Domain.Entities.Order", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("TEXT");

                    b.Property<int>("Status")
                        .HasColumnType("INTEGER");

                    b.HasKey("Id");

                    b.ToTable("Orders", (string)null);
                });

            modelBuilder.Entity("TechStoreOrders.Domain.Entities.Product", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("TEXT");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(150)
                        .HasColumnType("TEXT");

                    b.Property<decimal>("PriceEur")
                        .HasColumnType("decimal(18,2)");

                    b.Property<int>("Stock")
                        .HasColumnType("INTEGER");

                    b.HasKey("Id");

                    b.ToTable("Products", (string)null);

                    b.HasData(
                        new
                        {
                            Id = new Guid("9ddbf7b4-6d18-4ab5-b5c5-43a4a4be84bb"),
                            Name = "Running Sneakers",
                            PriceEur = 120m,
                            Stock = 40
                        },
                        new
                        {
                            Id = new Guid("9fdc765e-f7b5-49e6-925e-ef0a0a18a6d0"),
                            Name = "Basic T-Shirt",
                            PriceEur = 30m,
                            Stock = 120
                        },
                        new
                        {
                            Id = new Guid("3ae0ab8d-5b07-4b2d-be2d-5f6aa3f27a51"),
                            Name = "Cotton Socks",
                            PriceEur = 10m,
                            Stock = 300
                        },
                        new
                        {
                            Id = new Guid("d3a08c3f-d32b-4c7e-ac4a-8a4d5e8b1f37"),
                            Name = "Slim Jeans",
                            PriceEur = 65m,
                            Stock = 80
                        },
                        new
                        {
                            Id = new Guid("1a6b7fee-972a-47cf-9185-a8ac2e10cf9b"),
                            Name = "Hoodie",
                            PriceEur = 75m,
                            Stock = 60
                        });
                });

            modelBuilder.Entity("TechStoreOrders.Domain.Entities.Order", b =>
                {
                    b.OwnsMany("TechStoreOrders.Domain.Entities.OrderItem", "Items", b1 =>
                        {
                            b1.Property<int>("Id")
                                .ValueGeneratedOnAdd()
                                .HasColumnType("INTEGER");

                            b1.Property<Guid>("OrderId")
                                .HasColumnType("TEXT");

                            b1.Property<Guid>("ProductId")
                                .HasColumnType("TEXT");

                            b1.Property<int>("Quantity")
                                .HasColumnType("INTEGER");

                            b1.Property<decimal>("UnitPriceSnapshotEur")
                                .HasColumnType("decimal(18,2)");

                            b1.HasKey("Id");

                            b1.HasIndex("OrderId");

                            b1.ToTable("OrderItems", (string)null);

                            b1.WithOwner()
                                .HasForeignKey("OrderId");
                        });

                    b.Navigation("Items");
                });
#pragma warning restore 612, 618
        }
    }
}
